[project]
name = "pymupdf-md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymupdf>=1.26.4",
    "scikit-learn>=1.7.2",
]
